# H2 Database
# DataSource
spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:assignmentDB
spring.datasource.url=jdbc:h2:file:~/assignmentDB
#spring.datasource.url=jdbc:h2:mem:assignmentDB;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.password=${PASSWORD}

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# actuator health
management.endpoint.health.show-details=always

#S3
spring.cloud.aws.s3.bucket=cloud-assignment-thdud001012-files
